### PR TITLE
Add svg version of logo.

### PR DESCRIPTION
**Pull request by QuLogic**
Hey Lina, here's a _rough_ approximation of the logo in SVG format. It does not completely reproduce the text and font because I do not know what you used. If you let me know, I can update this one, or we could just regenerate the logos from this one.

If you accept this PR, it should show up automatically in UofTCoders/studyGroup#47 (but let me know if you want to change the text first.)

### CODE REVIEW

**Comment by linamnt** [comment]
I'm not particularly attached to the text I used, and it wasn't actually one text, but lots of different text boxes so that might be annoying for you? I can send them over to you though!

**Comment by linamnt** [comment]
Here they are: 
y1 <- cumsum(rnorm(100))
y2 <- cumsum(rnorm(100, mean=0.2))
par(mai=c(.8, .8, .2, .8)) library(gg
plot(1:100, y1, type="l", col="blue", xlab="X axis label", ylab="Left legend")
par(new=TRUE) plot(1:100, y2, type="l", ann=FALSE, yaxt="n")
axis(4) legend(x="topleft", bty="n", lty=c(1,1), col=c("blue","black"),
       legend=c("String 1 (left scale)", "String 2 (right scale)"))

const = digamma(N)-digamma(k) + d_log(2)
return (const + d_np.mean(map(log,nn)))/log(base)

import unittest
def median(pool):
    copy = sorted(pool)
    size = len(copy)
    if size % 2 == 1:
   l>div> return copy[(size - 1) / 2]
    else:   [for i in i
        return (copy[size/2 - 1] + copy[size/2]) / 2
class TestMedian(unittest.TestCase):
<!DOCTYPE html>
<html> for i in c:
<body>   print

<h1>My First Web Page</h1>

<p>My first paragraph.</p>

<script> df <- read.csv
document.write(5 + 6);
</script> <body>
</body>
</html>

**Comment by lwjohnst86** [comment]
I merged the https://github.com/UofTCoders/studyGroup/pull/47# PR, this can be another PR (as suggested by @jladan)

**Comment by QuLogic** [comment]
Let's move this to UofTCoders, then...

**Pull request closed without merging**
